'use client';

import { motion } from 'framer-motion';
import { FileText, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
            <div className="max-w-4xl mx-auto px-4 py-12">
                <Link href="/" className="inline-flex items-center gap-2 text-primary-600 hover:text-primary-700 mb-8">
                    <ArrowLeft className="w-4 h-4" />
                    Back to Home
                </Link>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                    <div className="flex items-center gap-3 mb-6">
                        <div className="p-3 bg-primary-100 rounded-xl">
                            <FileText className="w-6 h-6 text-primary-600" />
                        </div>
                        <h1 className="text-3xl font-bold text-slate-800">Terms of Service</h1>
                    </div>

                    <p className="text-slate-500 mb-8">Last updated: December 12, 2024</p>

                    <div className="prose prose-slate max-w-none">
                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">1. Acceptance of Terms</h2>
                            <p className="text-slate-600 mb-4">
                                By accessing or using ReAssist (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">2. Description of Service</h2>
                            <p className="text-slate-600 mb-4">
                                ReAssist is an AI-powered research assistant that provides comprehensive research analysis, source citations, and insights on various topics. The Service uses artificial intelligence to generate research reports based on user queries.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">3. User Responsibilities</h2>
                            <p className="text-slate-600 mb-4">You agree to:</p>
                            <ul className="list-disc pl-6 text-slate-600 space-y-2">
                                <li>Provide accurate account information</li>
                                <li>Maintain the security of your account credentials</li>
                                <li>Use the Service only for lawful purposes</li>
                                <li>Not attempt to bypass any security measures</li>
                                <li>Not use the Service to generate harmful or misleading content</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">4. Intellectual Property</h2>
                            <p className="text-slate-600 mb-4">
                                The Service and its original content, features, and functionality are owned by ReAssist and are protected by international copyright, trademark, and other intellectual property laws. Research reports generated by the Service are provided for your personal use.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">5. Disclaimer of Warranties</h2>
                            <p className="text-slate-600 mb-4">
                                The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee the accuracy, completeness, or usefulness of any research output. AI-generated content should be verified independently for critical decisions.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">6. Limitation of Liability</h2>
                            <p className="text-slate-600 mb-4">
                                ReAssist shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">7. Termination</h2>
                            <p className="text-slate-600 mb-4">
                                We reserve the right to terminate or suspend your account at any time for violations of these Terms. You may also terminate your account at any time by contacting us.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">8. Changes to Terms</h2>
                            <p className="text-slate-600 mb-4">
                                We may update these Terms from time to time. We will notify you of any changes by posting the new Terms on this page with an updated revision date.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-semibold text-slate-800 mb-4">9. Contact Us</h2>
                            <p className="text-slate-600">
                                If you have any questions about these Terms, please contact us at{' '}
                                <a href="mailto:legal@reassist.ai" className="text-primary-600 hover:underline">
                                    legal@reassist.ai
                                </a>
                            </p>
                        </section>
                    </div>
                </motion.div>
            </div>
        </div>
    );
}
